### ISSUE TITLE
what is the header key for authentication using cURL? 

### ISSUE THREAD

**Issue by SCLDev** [DumpYourPhoto/API-Documentation#3]
Hi, I am trying to use my api key in the header, but the documentation doesn't mention any reference to the key for it. I tried api_key, Authentication, Authorisation, with no success. 

Many thanks in advance for any lights shed on the subject.

Sep

**Comment by RamyTalal** [comment]
Try:
`https://api.dumpyourphoto.com/v1/an-endpoint?api_key=yourkeyhere`

**Comment by SCLDev** [comment]
Hi, 

Fantastic, that worked. Thanks a lot!

 I've got another question, what should I use for uploading an image in an album? I used: https://api.dumpyourphoto.com/v1/album/ALBUM'S HASH/photo?api_key=MY API" but it's giving me the 405 error. What shall I do? 

Much appreciated

PS. For the sake of organisation, shall I open another issue?

**Comment by RamyTalal** [comment]
The correct URL is:
`https://api.dumpyourphoto.com/v1/albums/youralbumhash/photos?api_key=yourkey`

And don't forget to add the `Content-Type: multipart/form-data` header.

**Comment by SCLDev** [comment]
That damn 's'!! :) I've been banging my head to the wall for the past hour!!! :) 

Thank you very much

**Comment by RamyTalal** [comment]
Glad to help and thank you for using the website!
